### ISSUE TITLE
re: the inventory stuff. typo im guessing?

### ISSUE THREAD

**Issue by csDaniel** [technicallyrice27/cs419_text_adventure#4]
"λ launch.py
Traceback (most recent call last):
  File "C:\Users\Dan\Documents\OSU\cs419\cs419_text_adventure\launch.py", line 1, in <module>
    from game import Game
  File "C:\Users\Dan\Documents\OSU\cs419\cs419_text_adventure\game.py", line 309
    print(i.name,end="\t")
                    ^
SyntaxError: invalid syntax"

**Comment by technicallyrice27** [comment]
Oh yeah this is definitely a python thing - maybe a version issue? Try running with python3 filename or update python3 (or download it!)
